### ISSUE TITLE
handleDMVRedirect is broken

### ISSUE THREAD

**Issue by shockey** [vartan/ca-dmv-poller#6]
Getting this error:

```
→ node poll.js 
Checking every 3 minutes, at DMV offices 25 miles from 90021
Will text [redacted] when a match is found.
/Users/kyle/ca-dmv-poller/poll.js:218
          var elements = window.document.forms[0].elements;
                                                 ^

TypeError: Cannot read property 'elements' of undefined
    at Object.done (/Users/kyle/ca-dmv-poller/poll.js:218:50)
    at process.nextTick (/Users/kyle/node_modules/jsdom/lib/jsdom.js:271:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Here's my config: 

```
{
    "behindTheWheelTest": false,
    "maxDistanceMiles":   25,
    "checkEveryMinutes":  3,
    "secondsBetweenRequests": 1,
    "findAppointmentWithinDays": 7,
    "home":       "90021",
    "textOnFind": true,
    "textNumber": "xxxxxxxxxx",
    "appointmentInfo": {
        "firstName":  "Kyle",
        "lastName":   "Shockey",
        "telArea":    "xxx",
        "telPrefix":  "xxx",
        "telSuffix":  "xxxx",
        "_comment":
            "ONLY HAVE TO FILL BELOW FOR BEHIND THE WHEEL TEST, two digit day/month",
        "dlNumber":   "",
        "birthMonth": "",
        "birthDay":   "",
        "birthYear":  ""
    },
    "dayOfWeeks": [
        {
            "name":       "Sunday",
            "allowed":    true,
            "startHour":  9,
            "endHour":    17

        },
        {
            "name":       "Monday",
            "allowed":    true,
            "startHour":  9,
            "endHour":    17
        },
        {
            "name":       "Tuesday",
            "allowed":    true,
            "startHour":  9,
            "endHour":    17
        },
        {
            "name":       "Wednesday",
            "allowed":    true,
            "startHour":  9,
            "endHour":    17
        },
        {
            "name":       "Thursday",
            "allowed":    true,
            "startHour":  9,
            "endHour":    17
        },
        {
            "name":        "Friday",
            "allowed":     true,
            "startHour":  9,
            "endHour":    17
        },
        {
            "name":       "Saturday",
            "allowed":    true,
            "startHour":  9,
            "endHour":    17
        }
    ]
}

```

**Comment by nsnitesh7** [comment]
I am also getting the same error. Did you find out the fix for this error?

**Comment by shockey** [comment]
I haven't - but it looks like the DMV is blocking JavaScriptless browsers now, and I don't see any flags for enabling JSDom's (dangerous) script execution options.

@vartan, any thoughts?

**Comment by mirca** [comment]
same error here
